### ISSUE TITLE
Sorry but

### ISSUE THREAD

**Issue by WaGi-Coding** [ericvb/Arduino-WavGat-Drivers#2]
Sorry for writing here since it's not an actual issue. I bought the crap wavgat arduino pro mini fakes and i am very disappointed as you ^^

You know some 100% Arduino compatible cheap chinese clone from aliexpress? I won't fall for such bad one again :/

Greetings from Vienna

**Comment by ericvb** [comment]
The latest chinese 100% compatible Arduino Uno I bought: 
https://www.aliexpress.com/item/32830661533.html?spm=a2g0s.9042311.0.0.27424c4dOT7e51
Until now, the Wavgat Arduino's were the only ones that weren't compatible.
So for the pro mini, simple search on the AliExpress webshop and don't select a Wavgat one :-)

**Comment by WaGi-Coding** [comment]
Thanks alot :)

ericvb <notifications@github.com> schrieb am Do., 23. Apr. 2020, 22:20:
